#spring.application.name=journalApp
#spring.mongodb.uri=mongodb+srv://mubbfahmeeda_db_user:o8sLWTOJ7tDr3eHu@cluster0.dxyqm2i.mongodb.net/?appName=Cluster0
#spring.mongodb.database=journaldb
#spring.mongodb.auto-index-creation=true

